name: python-ga
on: push
  # pull_request:
  #   types: [opened, synchronize]
jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6.10'
      - name: move to app
        run: cd app
      - name: install pipenv
        run: pip install pipenv
      - name: install dependencies
        run: pipenv install
      - name: run unit test
        run: python -m unittest discover ./test/unit_test

